CREATE SCHEMA IF NOT EXISTS LAB_PIPELINE.RAW;

GRANT USAGE ON SCHEMA LAB_PIPELINE.RAW TO ROLE AIRFLOW_DEV;

GRANT USAGE ON SCHEMA LAB_PIPELINE.RAW TO ROLE AIRFLOW_DEV;
GRANT CREATE FILE FORMAT ON SCHEMA LAB_PIPELINE.RAW TO ROLE AIRFLOW_DEV;

GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA LAB_PIPELINE.RAW TO ROLE AIRFLOW_DEV;

CREATE TABLE LAB_PIPELINE.RAW.STG_INMET_DATA (
    RAW_DATA VARIANT
);

CREATE TABLE LAB_PIPELINE.RAW.INMET_STAGE (
    RAW_DATA VARIANT
);

SELECT * FROM LAB_PIPELINE.RAW.STG_INMET_DATA;


GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA LAB_PIPELINE.RAW_STAGE TO ROLE AIRFLOW_DEV;
SELECT * FROM RAW_STAGE.INMET_STAGE_RAW;

GRANT USAGE ON SCHEMA LAB_PIPELINE.RAW TO ROLE AIRFLOW_DEV;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA LAB_PIPELINE.RAW TO ROLE AIRFLOW_DEV;

GRANT TRUNCATE ON TABLE LAB_PIPELINE.RAW.STG_INMET_DATA TO ROLE AIRFLOW_DEV;
GRANT INSERT ON TABLE LAB_PIPELINE.RAW.STG_INMET_DATA TO ROLE AIRFLOW_DEV;



GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA LAB_PIPELINE.RAW TO ROLE AIRFLOW_DEV;
SELECT * FROM LAB_PIPELINE.RAW.STG_INMET_DATA;

GRANT ON ALL STAGES IN SCHEMA LAB_PIPELINE.RAW TO ROLE AIRFLOW_DEV;
GRANT ALL PRIVILEGES ON STAGE STAGE_RAW TO ROLE AIRFLOW_DEV;

SELECT * FROM RAW.STG_INMET_DATA;

SELECT COUNT(*) FROM RAW.STG_INMET_DATA;

